_extends: .github

repository:
  name: NucleosAntiSpamBundle
  description: 🛡️ This bundle provides some basic features to reduce spam in symfony forms.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, php, antispam, spam, form, protection
